### ISSUE TITLE
[UI] Create `useGetOrders` in `orders` service

### ISSUE THREAD

**Issue by sebastian-nunez** [sockify/sockify#80]
### Description

Create the API integration required to get all orders and get an individual order from the UI.

### Acceptance criteria

- File location: `/web-client/src/api/orders`
- Create the needed models (`/web-client/src/api/orders/model.ts`) using `zod`
  - Zod schemas and types: `Order`, `OrdersPaginatedResponse`
  - Enum: `OrderStatus`
- Create the following queries (`/web-client/src/api/orders/queries.ts`):
   - `useGetOrders()`, `useGetOrderById(orderId)`
- Create the `OrderService` interface and implement it through a `HttpOrderService`. With these methods:
  - `getOrders(status: OrderStatus, limit: number, offset: number): Promise<OrdersPaginatedReponse>`

_Note: these are just suggestion for the required models, functions, etc. you may have to add/edit as needed_

**Comment by CharlotteW923** [comment]
Code changes:
https://github.com/sockify/sockify/pull/98
